### ISSUE TITLE
Unable to find token when theme used as fallback

### ISSUE THREAD

**Issue by justintemps** [un-core/designsystem#19]
With this configuration
```scss
// Includes some font settings
$css--body: true;
$css--reset: true;

@use "@un/styles/scss/config" with (
  $prefix: "ilo"
);

@use "@un/themes/scss/themes" as themes with (
  $custom-property-prefix: "ilo"
);

@use "@un/styles/scss/theme" with (
  $fallback: themes.$carbon--theme--white,
  $theme: (
    button-primary: red,
  )
);

@use "@un/styles/scss/components";

$carbon--theme: themes.$carbon--theme--wfp;

:root {
  @include themes.carbon--theme(themes.$carbon--theme--wfp, true) {
  }
}
```

We get an error like this:

```bash
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: "Unable to find token: layer-01 in current $theme"
   ╷
18 │     @return var(--#{config.$prefix}-#{$token}, #{theme.get($token)});
   │                                                  ^^^^^^^^^^^^^^^^^
   ╵
  ../../../designsystem/packages/themes/scss/modules/generated/_tokens.scss 18:50  -get()
  ../../../designsystem/packages/themes/scss/modules/generated/_tokens.scss 47:12  @forward
  ../../../designsystem/packages/themes/scss/modules/_tokens.scss 8:1              @forward
  ../../../designsystem/packages/styles/scss/_theme.scss 19:1                      @use
  ../styles/scss/index.scss 13:1                                                   @import
  .storybook/styles.scss 1:9                                                       root stylesheet
```
